development: &local
  adapter: postgresql
  database: takirails
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: takirails
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: takirails
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000
